# Form implementation generated from reading ui file 'app_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        Form.setStyleSheet("QWidget {\n"
"background-color: #F9E2AF\n"
"}")
        self.graphicsView = QtWidgets.QGraphicsView(parent=Form)
        self.graphicsView.setGeometry(QtCore.QRect(75, 20, 350, 210))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(150, 250, 171, 21))
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(parent=Form)
        self.spinBox.setGeometry(QtCore.QRect(120, 330, 42, 22))
        self.spinBox.setStyleSheet("background-color: #FFFFFF")
        self.spinBox.setObjectName("spinBox")
        self.comboBox = QtWidgets.QComboBox(parent=Form)
        self.comboBox.setGeometry(QtCore.QRect(170, 330, 81, 22))
        self.comboBox.setStyleSheet("background-color: #FFFFFF")
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(260, 330, 75, 23))
        self.pushButton.setStyleSheet("background-color: #FFFFFF")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 360, 91, 23))
        self.pushButton_2.setStyleSheet("background-color: #FFFFFF")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 250, 41, 23))
        self.pushButton_3.setStyleSheet("background-color: #FFFFFF")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "5⭐ Calculator"))
        self.label.setText(_translate("Form", "more reviews for a 5⭐ average."))
        self.pushButton.setText(_translate("Form", "Add Reviews"))
        self.pushButton_2.setText(_translate("Form", "Subtract Reviews"))
        self.pushButton_3.setText(_translate("Form", "Totals"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
